addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.3.3")
addSbtPlugin("com.dwijnand"       % "sbt-travisci"   % "1.1.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"    % "0.6.22")
addSbtPlugin("com.47deg"          % "sbt-microsites" % "0.7.23")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"   % "1.5.1")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.2.1")
