addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.2.27")
addSbtPlugin("com.dwijnand"       % "sbt-travisci"   % "1.1.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"    % "0.6.21")
addSbtPlugin("com.47deg"          % "sbt-microsites" % "0.7.15")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"   % "1.4.0")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"     % "3.0.0")
