addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.4")
addSbtPlugin("com.dwijnand"       % "sbt-travisci"             % "1.1.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.24")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("com.47deg"          % "sbt-microsites"           % "0.7.20")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"             % "1.5.1")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"               % "3.0.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.9.0")
