package scalaz
package newtypes

object Newtypes extends Newtypess

trait Newtypess extends
BigIntegerMultiplications with
BigIntMultiplications with
BooleanConjunctions with
ByteMultiplications with
CharMultiplications with
Duals with
FirstLazyOptions with
FirstOptions with
IntMultiplications with
LastLazyOptions with
LastOptions with
LongMultiplications with
ShortMultiplications with
ZipStreams
