name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.repository_owner == 'scalaz' }}
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      with:
        client-id: 89659
        private-key: ${{ secrets.SCALAZ_BOT_KEY }}
    - uses: sbt/setup-sbt@93e926cbdb4a428e41b4ef754124ec82925ffdc2 # v1.1.23
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@b186ab858ce163f9af7b016fac32cfb3f2c2f503 # v2.88.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74843977+scalaz-bot[bot]@users.noreply.github.com"
        author-name: scalaz-bot[bot]
        branches: master,series/7.3.x,series/7.2.x
