name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.repository_owner == 'scalaz' }}
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: 89659
        private-key: ${{ secrets.SCALAZ_BOT_KEY }}
    - uses: sbt/setup-sbt@2e222825582620cc38d2a54e674f3c01b7c14f5d # v1.1.24
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@708c1d682b14b9785201afb25c8ffece0a9d126f # v2.90.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74843977+scalaz-bot[bot]@users.noreply.github.com"
        author-name: scalaz-bot[bot]
        branches: master,series/7.3.x,series/7.2.x
